Generated delete query for context 'Assemblies': DELETE FROM Assemblies WHERE AssemblyID = :AssemblyID
Generated queries for context 'Assemblies': {'fetch_query': 'SELECT AssemblyID, AssemName, ParentAssemblyID, AssemImageRef, AssemDwgID, AssemCost, AssemWeight, AssemHoursParts, AssemHoursAssembly, AssemTotalHours, AssemFocus, AssemCostFlag, AssemWeightFlag, AssemStatus, AssemNotes FROM Assemblies', 'insert_query': 'INSERT INTO Assemblies (AssemName, ParentAssemblyID, AssemImageRef, AssemDwgID, AssemCost, AssemWeight, AssemHoursParts, AssemHoursAssembly, AssemTotalHours, AssemFocus, AssemCostFlag, AssemWeightFlag, AssemStatus, AssemNotes) VALUES (:AssemName, :ParentAssemblyID, :AssemImageRef, :AssemDwgID, :AssemCost, :AssemWeight, :AssemHoursParts, :AssemHoursAssembly, :AssemTotalHours, :AssemFocus, :AssemCostFlag, :AssemWeightFlag, :AssemStatus, :AssemNotes)', 'update_query': 'UPDATE Assemblies SET AssemName = :AssemName, ParentAssemblyID = :ParentAssemblyID, AssemImageRef = :AssemImageRef, AssemDwgID = :AssemDwgID, AssemCost = :AssemCost, AssemWeight = :AssemWeight, AssemHoursParts = :AssemHoursParts, AssemHoursAssembly = :AssemHoursAssembly, AssemTotalHours = :AssemTotalHours, AssemFocus = :AssemFocus, AssemCostFlag = :AssemCostFlag, AssemWeightFlag = :AssemWeightFlag, AssemStatus = :AssemStatus, AssemNotes = :AssemNotes WHERE AssemblyID = :AssemblyID', 'delete_query': 'DELETE FROM Assemblies WHERE AssemblyID = :AssemblyID'}
get_processed_column_definitions called with:
  column_definitions: {'AssemblyID': {'display_name': 'ID', 'width': 60, 'type': 'int', 'is_primary_key': True}, 'AssemName': {'display_name': 'Name', 'width': 200, 'type': 'string'}, 'ParentAssemblyID': {'display_name': 'Parent Assembly', 'width': 100, 'type': 'int'}, 'AssemImageRef': {'display_name': 'Image Reference', 'width': 150, 'type': 'string'}, 'AssemImage': {'display_name': 'Image', 'width': 150, 'type': 'blob', 'admin': True}, 'AssemDwgID': {'display_name': 'Drawing ID', 'width': 100, 'type': 'string'}, 'AssemCost': {'display_name': 'Cost', 'width': 80, 'type': 'numeric'}, 'AssemWeight': {'display_name': 'Weight', 'width': 80, 'type': 'numeric'}, 'AssemHoursParts': {'display_name': 'Hours (Parts)', 'width': 100, 'type': 'numeric', 'default': 0}, 'AssemHoursAssembly': {'display_name': 'Hours (Assembly)', 'width': 100, 'type': 'numeric', 'default': 0}, 'AssemTotalHours': {'display_name': 'Total Hours', 'width': 100, 'type': 'numeric'}, 'AssemFocus': {'display_name': 'Focus', 'width': 100, 'type': 'string', 'default': 'Medium'}, 'AssemCostFlag': {'display_name': 'Cost Flag', 'width': 80, 'type': 'int', 'default': 0}, 'AssemWeightFlag': {'display_name': 'Weight Flag', 'width': 80, 'type': 'int', 'default': 0}, 'AssemStatus': {'display_name': 'Status', 'width': 100, 'type': 'string', 'default': 'Prelim'}, 'AssemNotes': {'display_name': 'Notes', 'width': 200, 'type': 'string'}, 'CreationDate': {'display_name': 'Creation Date', 'width': 120, 'type': 'string', 'default': '2025-01-01', 'admin': True}, 'LastUpdatedDate': {'display_name': 'Last Updated Date', 'width': 120, 'type': 'string', 'default': '2025-01-01', 'admin': True}} (type: <class 'dict'>)
  exclude_hidden: True
Processing column definitions: {'AssemblyID': {'display_name': 'ID', 'width': 60, 'type': 'int', 'is_primary_key': True}, 'AssemName': {'display_name': 'Name', 'width': 200, 'type': 'string'}, 'ParentAssemblyID': {'display_name': 'Parent Assembly', 'width': 100, 'type': 'int'}, 'AssemImageRef': {'display_name': 'Image Reference', 'width': 150, 'type': 'string'}, 'AssemImage': {'display_name': 'Image', 'width': 150, 'type': 'blob', 'admin': True}, 'AssemDwgID': {'display_name': 'Drawing ID', 'width': 100, 'type': 'string'}, 'AssemCost': {'display_name': 'Cost', 'width': 80, 'type': 'numeric'}, 'AssemWeight': {'display_name': 'Weight', 'width': 80, 'type': 'numeric'}, 'AssemHoursParts': {'display_name': 'Hours (Parts)', 'width': 100, 'type': 'numeric', 'default': 0}, 'AssemHoursAssembly': {'display_name': 'Hours (Assembly)', 'width': 100, 'type': 'numeric', 'default': 0}, 'AssemTotalHours': {'display_name': 'Total Hours', 'width': 100, 'type': 'numeric'}, 'AssemFocus': {'display_name': 'Focus', 'width': 100, 'type': 'string', 'default': 'Medium'}, 'AssemCostFlag': {'display_name': 'Cost Flag', 'width': 80, 'type': 'int', 'default': 0}, 'AssemWeightFlag': {'display_name': 'Weight Flag', 'width': 80, 'type': 'int', 'default': 0}, 'AssemStatus': {'display_name': 'Status', 'width': 100, 'type': 'string', 'default': 'Prelim'}, 'AssemNotes': {'display_name': 'Notes', 'width': 200, 'type': 'string'}, 'CreationDate': {'display_name': 'Creation Date', 'width': 120, 'type': 'string', 'default': '2025-01-01', 'admin': True}, 'LastUpdatedDate': {'display_name': 'Last Updated Date', 'width': 120, 'type': 'string', 'default': '2025-01-01', 'admin': True}}
Processed columns for context 'Assemblies': {'AssemblyID': {'display_name': 'ID', 'width': 60, 'type': 'int', 'is_primary_key': True}, 'AssemName': {'display_name': 'Name', 'width': 200, 'type': 'string'}, 'ParentAssemblyID': {'display_name': 'Parent Assembly', 'width': 100, 'type': 'int'}, 'AssemImageRef': {'display_name': 'Image Reference', 'width': 150, 'type': 'string'}, 'AssemDwgID': {'display_name': 'Drawing ID', 'width': 100, 'type': 'string'}, 'AssemCost': {'display_name': 'Cost', 'width': 80, 'type': 'numeric'}, 'AssemWeight': {'display_name': 'Weight', 'width': 80, 'type': 'numeric'}, 'AssemHoursParts': {'display_name': 'Hours (Parts)', 'width': 100, 'type': 'numeric', 'default': 0}, 'AssemHoursAssembly': {'display_name': 'Hours (Assembly)', 'width': 100, 'type': 'numeric', 'default': 0}, 'AssemTotalHours': {'display_name': 'Total Hours', 'width': 100, 'type': 'numeric'}, 'AssemFocus': {'display_name': 'Focus', 'width': 100, 'type': 'string', 'default': 'Medium'}, 'AssemCostFlag': {'display_name': 'Cost Flag', 'width': 80, 'type': 'int', 'default': 0}, 'AssemWeightFlag': {'display_name': 'Weight Flag', 'width': 80, 'type': 'int', 'default': 0}, 'AssemStatus': {'display_name': 'Status', 'width': 100, 'type': 'string', 'default': 'Prelim'}, 'AssemNotes': {'display_name': 'Notes', 'width': 200, 'type': 'string'}}
Tab 'Assemblies' successfully added to the notebook
Configuring Treeview column: AssemblyID, Details: {'display_name': 'ID', 'width': 60, 'type': 'int', 'is_primary_key': True}
Configuring Treeview column: AssemName, Details: {'display_name': 'Name', 'width': 200, 'type': 'string'}
Configuring Treeview column: ParentAssemblyID, Details: {'display_name': 'Parent Assembly', 'width': 100, 'type': 'int'}
Configuring Treeview column: AssemImageRef, Details: {'display_name': 'Image Reference', 'width': 150, 'type': 'string'}
Configuring Treeview column: AssemDwgID, Details: {'display_name': 'Drawing ID', 'width': 100, 'type': 'string'}
Configuring Treeview column: AssemCost, Details: {'display_name': 'Cost', 'width': 80, 'type': 'numeric'}
Configuring Treeview column: AssemWeight, Details: {'display_name': 'Weight', 'width': 80, 'type': 'numeric'}
Configuring Treeview column: AssemHoursParts, Details: {'display_name': 'Hours (Parts)', 'width': 100, 'type': 'numeric', 'default': 0}
Configuring Treeview column: AssemHoursAssembly, Details: {'display_name': 'Hours (Assembly)', 'width': 100, 'type': 'numeric', 'default': 0}
Configuring Treeview column: AssemTotalHours, Details: {'display_name': 'Total Hours', 'width': 100, 'type': 'numeric'}
Configuring Treeview column: AssemFocus, Details: {'display_name': 'Focus', 'width': 100, 'type': 'string', 'default': 'Medium'}
Configuring Treeview column: AssemCostFlag, Details: {'display_name': 'Cost Flag', 'width': 80, 'type': 'int', 'default': 0}
Configuring Treeview column: AssemWeightFlag, Details: {'display_name': 'Weight Flag', 'width': 80, 'type': 'int', 'default': 0}
Configuring Treeview column: AssemStatus, Details: {'display_name': 'Status', 'width': 100, 'type': 'string', 'default': 'Prelim'}
Configuring Treeview column: AssemNotes, Details: {'display_name': 'Notes', 'width': 200, 'type': 'string'}
Query executed successfully.